---
# tasks file for db
- name: Show info about the env this host belongs to
  debug: 
    msg: "This host is in {{ env }} environment!!!"
- name: Update repository
  apt_repository:
   repo: 'ppa:git-core/ppa'
   state: present
- name: Install git
  apt:
   name: git
   state: present
   update_cache: yes
- name: Change mongo config file
  template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
    mode: 0644
  notify: restart mongod